### ISSUE TITLE
Finish login sequence

### ISSUE THREAD

**Issue by mhsjlw** [fuzzy-octopus/mcpe-server#1]

**Comment by Creeplays** [comment]
Need to rewrite SERVER_HANDSHAKE and CLIENT_HANDSHAKE, but everywhere is wrong info. Also need to parse ACK packets.

**Comment by mhsjlw** [comment]
We still need to figure out the 12.1 login sequence. But now we have some protocol documentation to work with.

**Comment by Creeplays** [comment]
Where?

**Comment by mhsjlw** [comment]
@Creeplays https://github.com/mhsjlw/mcpe-protocol/blob/master/protocol/protocol.json

**Comment by rom1504** [comment]
it's not complete at all.

**Comment by mhsjlw** [comment]
I am aware but its better rhan nothing
